### ISSUE TITLE
Documentation is  not available anymore

### ISSUE THREAD

**Issue by dbayonacode** [powderblue/jquery-combogrid#2]
Could you please enable a link where the documentation is available. The current link has been disabled.

**Comment by danbettles** [comment]
Hello

The only documentation I know of is in the HTML files in the root of the project.  Combogrid is no longer maintained, or hosted, by the author, and we don't intend maintaining it, either -- not really.  We posted the source on GitHub so that we could continue using our existing package manager set-up and because the source may be useful for others.

Best,
Dan
